# Generated by Django 3.2.3 on 2021-05-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('PODCAST', 'Podcast'), ('MUSIC', 'Music'), ('YOUTUBE', 'YouTube')], max_length=7, null=True),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['last_accessed'], name='api_link_last_ac_135e3f_idx'),
        ),
    ]
