# Generated by Django 3.2.3 on 2021-07-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210608_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
