# Generated by Django 3.2.3 on 2021-07-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(null=True, unique=True),
        ),
    ]
