# Generated by Django 3.2.3 on 2022-04-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_link_add_start_time_in_sec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='start_time_in_sec',
            new_name='start_time',
        ),
    ]
